In [82]:
import numpy as np
import pandas as pd
import scipy.stats as stats
import matplotlib.pyplot as plt
import seaborn as sns
from matplotlib import colormaps  # Import colormaps

pd.options.display.float_format = '{:,.2f}'.format
# ปิดการแสดงคำเตือน SettingWithCopyWarning ชั่วคราว
pd.options.mode.chained_assignment = None  # ปิดการแสดงคำเตือน

from sklearn.metrics import precision_score



In [83]:

from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score, classification_report

from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, confusion_matrix, classification_report


In [84]:

# อ่านข้อมูลจากไฟล์ CSV
df = pd.read_csv('Target Payment Product.csv')  # แทนที่ 'your_file.csv' ด้วยชื่อไฟล์ของคุณ


In [85]:
df.columns

Index(['ACCOUNT_NO', 'SERVICED_NUMBER', 'PAYMENT_DATE', 'INVOICE_DATE',
       'PAY_TYPE', 'payment_type', 'AMOUNT', 'DAYS_DIFF', 'TEL_NO',
       'PRODUCT DESC', 'ACCOUNT_TYPE', 'BANK_CODE', 'CUSTOMER_REF',
       'SERVICE_LOCATION NAME', 'INACTIVE_DATE', 'ACTIVE_DATE', 'AMOUNT_DUE'],
      dtype='object')

In [86]:
df.dtypes

ACCOUNT_NO                 int64
SERVICED_NUMBER           object
PAYMENT_DATE              object
INVOICE_DATE              object
PAY_TYPE                  object
payment_type              object
AMOUNT                   float64
DAYS_DIFF                  int64
TEL_NO                    object
PRODUCT DESC              object
ACCOUNT_TYPE              object
BANK_CODE                 object
CUSTOMER_REF              object
SERVICE_LOCATION NAME     object
INACTIVE_DATE             object
ACTIVE_DATE               object
AMOUNT_DUE               float64
dtype: object

In [87]:
# แปลงคอลัมน์ 'PAYMENT_DATE' และ 'INVOICE_DATE' เป็น datetime
df['PAYMENT_DATE'] = pd.to_datetime(df['PAYMENT_DATE'])
df['INVOICE_DATE'] = pd.to_datetime(df['INVOICE_DATE'])

In [88]:
df.columns

Index(['ACCOUNT_NO', 'SERVICED_NUMBER', 'PAYMENT_DATE', 'INVOICE_DATE',
       'PAY_TYPE', 'payment_type', 'AMOUNT', 'DAYS_DIFF', 'TEL_NO',
       'PRODUCT DESC', 'ACCOUNT_TYPE', 'BANK_CODE', 'CUSTOMER_REF',
       'SERVICE_LOCATION NAME', 'INACTIVE_DATE', 'ACTIVE_DATE', 'AMOUNT_DUE'],
      dtype='object')

In [89]:
len(df)

629955

In [90]:
# สุ่มตัวอย่างข้อมูล (เช่น สุ่มตัวอย่าง 10% ของข้อมูล)
df = df.sample(frac=0.1, random_state=1)

In [91]:

# ลบคอลัมน์ที่ไม่จำเป็น
df.drop(['SERVICED_NUMBER', 'TEL_NO', 'PRODUCT DESC', 'ACCOUNT_TYPE', 'BANK_CODE', 'CUSTOMER_REF', 'SERVICE_LOCATION NAME', 'INACTIVE_DATE', 'ACTIVE_DATE', 'AMOUNT_DUE'], axis=1, inplace=True)

# แปลงคอลัมน์ PAY_TYPE และ payment_type เป็นตัวเลขโดยใช้ Label Encoding
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
df['PAY_TYPE'] = le.fit_transform(df['PAY_TYPE'])
df['payment_type'] = le.fit_transform(df['payment_type'])


In [92]:
df

ACCOUNT_NO PAYMENT_DATE INVOICE_DATE  PAY_TYPE  payment_type  \
62328      104196223   2022-12-19   2022-11-16         3             0   
87446      106560194   2022-06-27   2022-05-26         3             0   
436071  104529704316   2022-06-22   2022-05-21         3             0   
112800     107511609   2022-01-12   2021-12-11         4             0   
481819  104530662618   2022-12-13   2022-11-11         3             0   
...              ...          ...          ...       ...           ...   
350321     615786122   2022-07-14   2022-06-11         4             0   
201440     118026505   2022-07-12   2022-06-11         3             0   
405028    5500955435   2022-03-14   2022-02-10         3             0   
368880     620149516   2022-04-22   2022-03-21         3             0   
128951     108477852   2022-08-16   2022-07-11         4             0   

         AMOUNT  DAYS_DIFF  
62328    199.60         33  
87446    175.00         32  
436071 3,799.00         32  
112800   106.00         32  
481819   200.00         32  
...         ...        ...  
350321   100.00         33  
201440   150.00         31  
405028 3,812.00         32  
368880   220.00         32  
128951   700.00         36  

[62996 rows x 7 columns]

In [95]:

# กำหนด features (ตัวแปรอิสระ) และ target (ตัวแปรตาม)
# แบ่งข้อมูลออกเป็น features และ target
features = df.drop(['ACCOUNT_NO', 'PAYMENT_DATE', 'INVOICE_DATE'], axis=1)  # เอาคอลัมน์ 'ACCOUNT_NO', 'PAYMENT_DATE', 'INVOICE_DATE' ออกเพราะเป็นค่าแยกและไม่มีผลต่อการวิเคราะห์
target = df['PAY_TYPE']

# แบ่งข้อมูลเป็นชุด Train และ Test
X_train, X_test, y_train, y_test = train_test_split(features, target, test_size=0.2, random_state=42)

# สร้างแบบจำลอง Decision Tree Classifier
model = DecisionTreeClassifier()

# ฝึก (Train) แบบจำลอง
model.fit(X_train, y_train)

# ทำนายข้อมูลที่ใช้ Test
y_pred = model.predict(X_test)

# วัดประสิทธิภาพของโมเดล
accuracy = accuracy_score(y_test, y_pred)
precision = precision_score(y_test, y_pred, average='weighted')
recall = recall_score(y_test, y_pred, average='weighted')
f1 = f1_score(y_test, y_pred, average='weighted')
conf_matrix = confusion_matrix(y_test, y_pred)
class_report = classification_report(y_test, y_pred)

print(f"Accuracy: {accuracy}")
print(f"Precision: {precision}")
print(f"Recall: {recall}")
print(f"F1 Score: {f1}")
print("Confusion Matrix:")
print(conf_matrix)
print("Classification Report:")
print(class_report)





Accuracy: 1.0
Precision: 1.0
Recall: 1.0
F1 Score: 1.0
Confusion Matrix:
[[  37    0    0    0    0    0]
 [   0    1    0    0    0    0]
 [   0    0    4    0    0    0]
 [   0    0    0 9446    0    0]
 [   0    0    0    0 3062    0]
 [   0    0    0    0    0   50]]
Classification Report:
              precision    recall  f1-score   support

           0       1.00      1.00      1.00        37
           1       1.00      1.00      1.00         1
           2       1.00      1.00      1.00         4
           3       1.00      1.00      1.00      9446
           4       1.00      1.00      1.00      3062
           5       1.00      1.00      1.00        50

    accuracy                           1.00     12600
   macro avg       1.00      1.00      1.00     12600
weighted avg       1.00      1.00      1.00     12600



In [36]:
# แสดงรายงานการประเมิน
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

   100002342       0.00      0.00      0.00         1
   100003110       0.00      0.00      0.00         1
   100003776       0.00      0.00      0.00         1
   100020348       0.00      0.00      0.00         1
   100054275       0.00      0.00      0.00         1
   100054451       0.00      0.00      0.00         1
   100054567       0.00      0.00      0.00         1
   100055061       0.00      0.00      0.00         0
   100055168       0.00      0.00      0.00         0
   100056097       0.00      0.00      0.00         0
   100056185       0.00      0.00      0.00         1
   100056653       0.00      0.00      0.00         1
   100057616       0.00      0.00      0.00         1
   100058013       0.00      0.00      0.00         0
   100058679       0.00      0.00      0.00         1
   100060610       0.00      0.00      0.00         0
   100060975       0.00      0.00      0.00         2
   100063538       0.00    

/Users/seal/Library/Python/3.10/lib/python/site-packages/sklearn/metrics/_classification.py:1517: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/Users/seal/Library/Python/3.10/lib/python/site-packages/sklearn/metrics/_classification.py:1517: UndefinedMetricWarning: Recall is ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/Users/seal/Library/Python/3.10/lib/python/site-packages/sklearn/metrics/_classification.py:1517: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/Users